# After loading and unzip the database files
This lab show:
- How to add the location directory to the csv indexes files and concatenate them,
- How to load the data in Pytorch for training.

## Libs

In [1]:
import torch
from torchvision.transforms import transforms
import numpy as np
from torch.utils.data import Dataset, DataLoader, random_split
import pygimli as pg
import pandas as pd
import random
import os
%matplotlib inline

## Adding the path to the dataset and concat

In [33]:
## functions to add the path to the csv files indexes
def add_directory_to_df_os(data_names, directory, slice=list(np.arange(0,6)), verbose=True):
    """ replace or add the directory to the dataset file names to access to data using os """
    data_paths = data_names.copy()
    for c in slice:
        current_col = data_paths.iloc[:, c]
        data_paths.iloc[:, c] = list(map(lambda file: os.path.join( directory, os.path.basename(file)), current_col))
    # adding the indexes
    data_paths = data_paths.reset_index()
    if verbose:
        pg.info("The directory path has been added to the dataset names.")
    return data_paths

In [34]:
# loading and adding directory: file 1
csv_file_1 = pd.read_csv("/gpfs/projets/deepres/bdd_indexes/data_names_EA_part1.csv")
dir_loc_1 = "/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_EA_P1"
data_paths_1 = add_directory_to_df_os(csv_file_1, dir_loc_1, slice=list(np.arange(0,6)), verbose=True)
print(f"Number of data: {len(data_paths_1)}")
data_paths_1.head()

26/02/26 - 15:24:27 - pyGIMLi - INFO - The directory path has been added to the dataset names.

Number of data: 7474

,index,True resistivity img,True resistivity tri mesh,Rhoa pg file from slm with 2 % of noise,Pg pre-inversion of rhoa from slm with 2 % of noise,Rhoa pg file from dd with 2 % of noise,Pg pre-inversion of rhoa from dd with 2 % of noise,preInv_rmse_on_WS,preInv_rmse_on_DD
0,0,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,1.97618,12.12774
1,1,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,1.99706,8.45848
2,2,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,1.97678,1.99412
3,3,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,1.99683,1.97547
4,4,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,1.99226,2.01293

In [35]:
# loading and adding directory: file 2
csv_file_2 = pd.read_csv("/gpfs/projets/deepres/bdd_indexes/data_names_ML_part4.csv")
dir_loc_2 = "/gpfs/projets/deepres/Data/preInv_DCR_T0_WSnDD_ML_P4"
data_paths_2 = add_directory_to_df_os(csv_file_2, dir_loc_2, slice=list(np.arange(0,6)), verbose=True)
print(f"Number of data: {len(data_paths_2)}")
data_paths_2.head()

26/02/26 - 15:24:29 - pyGIMLi - INFO - The directory path has been added to the dataset names.

Number of data: 8713

,index,True resistivity img,True resistivity tri mesh,Rhoa pg file from slm with 2 % of noise,Pg pre-inversion of rhoa from slm with 2 % of noise,Rhoa pg file from dd with 2 % of noise,Pg pre-inversion of rhoa from dd with 2 % of noise,preInv_rmse_on_WS,preInv_rmse_on_DD
0,0,/gpfs/projets/deepres/Data/preInv_DCR_T0_WSnDD...,/gpfs/projets/deepres/Data/preInv_DCR_T0_WSnDD...,/gpfs/projets/deepres/Data/preInv_DCR_T0_WSnDD...,/gpfs/projets/deepres/Data/preInv_DCR_T0_WSnDD...,/gpfs/projets/deepres/Data/preInv_DCR_T0_WSnDD...,/gpfs/projets/deepres/Data/preInv_DCR_T0_WSnDD...,2.13230,2.05285
1,1,/gpfs/projets/deepres/Data/preInv_DCR_T0_WSnDD...,/gpfs/projets/deepres/Data/preInv_DCR_T0_WSnDD...,/gpfs/projets/deepres/Data/preInv_DCR_T0_WSnDD...,/gpfs/projets/deepres/Data/preInv_DCR_T0_WSnDD...,/gpfs/projets/deepres/Data/preInv_DCR_T0_WSnDD...,/gpfs/projets/deepres/Data/preInv_DCR_T0_WSnDD...,2.05535,2.76721
2,2,/gpfs/projets/deepres/Data/preInv_DCR_T0_WSnDD...,/gpfs/projets/deepres/Data/preInv_DCR_T0_WSnDD...,/gpfs/projets/deepres/Data/preInv_DCR_T0_WSnDD...,/gpfs/projets/deepres/Data/preInv_DCR_T0_WSnDD...,/gpfs/projets/deepres/Data/preInv_DCR_T0_WSnDD...,/gpfs/projets/deepres/Data/preInv_DCR_T0_WSnDD...,1.99821,2.16553
3,3,/gpfs/projets/deepres/Data/preInv_DCR_T0_WSnDD...,/gpfs/projets/deepres/Data/preInv_DCR_T0_WSnDD...,/gpfs/projets/deepres/Data/preInv_DCR_T0_WSnDD...,/gpfs/projets/deepres/Data/preInv_DCR_T0_WSnDD...,/gpfs/projets/deepres/Data/preInv_DCR_T0_WSnDD...,/gpfs/projets/deepres/Data/preInv_DCR_T0_WSnDD...,1.96334,1.98132
4,4,/gpfs/projets/deepres/Data/preInv_DCR_T0_WSnDD...,/gpfs/projets/deepres/Data/preInv_DCR_T0_WSnDD...,/gpfs/projets/deepres/Data/preInv_DCR_T0_WSnDD...,/gpfs/projets/deepres/Data/preInv_DCR_T0_WSnDD...,/gpfs/projets/deepres/Data/preInv_DCR_T0_WSnDD...,/gpfs/projets/deepres/Data/preInv_DCR_T0_WSnDD...,1.95342,1.93880

In [36]:
## concatenate the two dataframes
data_paths = pd.concat([data_paths_1, data_paths_2], ignore_index=True)
data_paths.reset_index()
print(f"Number of data: {len(data_paths)}")
data_paths.head()

Number of data: 16187

,index,True resistivity img,True resistivity tri mesh,Rhoa pg file from slm with 2 % of noise,Pg pre-inversion of rhoa from slm with 2 % of noise,Rhoa pg file from dd with 2 % of noise,Pg pre-inversion of rhoa from dd with 2 % of noise,preInv_rmse_on_WS,preInv_rmse_on_DD
0,0,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,1.97618,12.12774
1,1,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,1.99706,8.45848
2,2,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,1.97678,1.99412
3,3,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,1.99683,1.97547
4,4,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,/gpfs/scratch/ovonoekore/preInv_DCR_T0_WSnDD_E...,1.99226,2.01293

Note that you can concatenate more preInvDCR dataset parts, following the same process.

## Loading data for Pytorch

In [39]:
## setting the device
#device = torch.device('cuda' if torch.cuda.is_available() else 'cpu') # if you gpu device availabe
device = torch.device('cpu')
device

device(type='cpu')

In [40]:
## Class data
class device_img_preInvData(Dataset):
    """ Preload all the dataset in the (gpu) device at once to speed up training """
    def __init__(self, df_dataPaths, data_dir=None, transform_x=None, transform_y=None, decay_col=0, device=None):
        self.data_dir = data_dir
        self.df_dataPaths = df_dataPaths
        if data_dir:
            self.df_dataPaths = add_directory_to_df_os(df_dataPaths, data_dir)
            self.df_dataPaths = self.df_dataPaths.reset_index()
        self.len = self.df_dataPaths.shape[0]

        self.info_linked_id = torch.from_numpy(self.df_dataPaths.iloc[:, 0].values) # always stay on cpu
        self.x_images = torch.from_numpy(np.array(list(map(pd.read_csv, self.df_dataPaths.iloc[:, 1]))))
        self.y_images = torch.from_numpy(np.array(list(map(pd.read_csv, self.df_dataPaths.iloc[:, decay_col+4]))))
        
        self.transform_x = transform_x
        self.transform_y = transform_y
        if self.transform_x :
            self.x_images = torch.stack(list(map(self.transform_x, self.x_images))).to(dtype=torch.float)
        if self.transform_y :
            self.y_images = torch.stack(list(map(self.transform_y, self.y_images))).to(dtype=torch.float)
        
        self.device = device
        if self.device:
            self.x_images = self.x_images.to(self.device, non_blocking=True)
            self.y_images = self.y_images.to(self.device, non_blocking=True)
        
    def __len__(self):
        return self.len

    def __getitem__(self, index):
        x_image, y_image = self.x_images[index], self.y_images[index]
        info_linked_id = self.info_linked_id[index]
        return x_image, y_image, info_linked_id

In [41]:
## Normalized all the resistivities maps over the max resistivity in all the dataset
# this will help the training, accentuate resistivity contrast and avoid the loss explosion 
# by confinning the data in [0, 1]
class normRes(object):
    """ Normalize resistivities image by the max resistivity overall the dataset """
    def __init__(self, maxDatasetRes=1000.0, logScale=False, regulLog=0.0):
        self.logScale = logScale
        self.regulLog = regulLog  # to avoid log(0)
        if self.logScale:
            maxDatasetRes = np.log10(maxDatasetRes)
        self.maxDaatsetRes = torch.tensor([maxDatasetRes], dtype=torch.float32)

    def __call__(self, inIMG):
        if self.logScale:
            outIMG = torch.log10(inIMG+self.regulLog)/abs(self.maxDaatsetRes)
        else:
            outIMG = inIMG/self.maxDaatsetRes
        return outIMG

In [17]:
# transforms
normalizedOverMaxRes = normRes(maxDatasetRes=2010.0, logScale=True, regulLog=0.0)
norm_totensor_transform = transforms.Compose([normalizedOverMaxRes, transforms.Lambda(lambda x: x.unsqueeze(0))])
## DD dataset
dd_dataset = device_img_preInvData(data_paths, data_dir = None, transform_x = norm_totensor_transform
                                 , transform_y = norm_totensor_transform, decay_col=2)
## WS dataset
#ws_dataset = device_img_preInvData(data_paths, data_dir=None, transform_x = norm_totensor_transform
#                                 , transform_y = norm_totensor_transform, decay_col=0)

All your dataset is now loaded in your device

In [43]:
# Seeding the random(s) for reproductibility
def set_seed(seed=26):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    #torch.use_deterministic_algorithms(True)

seed=2026
set_seed(seed)
g = torch.Generator()
g.manual_seed(seed)

In [42]:
# splitting
N = len(dd_dataset)
train_size = int(0.8 * N)
val_size = int(0.1 * N)
test_size = N - train_size - val_size
batch_size = 32
train_set, val_set, test_set = random_split(dd_dataset, [train_size, val_size, test_size])
# loading 
trainload = DataLoader(train_set, batch_size=batch_size, shuffle=True, generator=g, pin_memory=False)#, num_workers=2)
valload = DataLoader(val_set, batch_size=batch_size, shuffle=False, pin_memory=False)#, num_workers=2)
testload = DataLoader(test_set, batch_size=batch_size, shuffle=False, pin_memory=False)#, num_workers=2)
print("Your data are ready for training")

Your data are ready for training